pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                dir('pro-track/module-02-jenkins/resources/python') {
                    sh 'pip install -r requirements.txt'
                    sh 'pytest'
                }
            }
        }
    }
}