FROM python:3.11-alpine

WORKDIR /app

RUN apk add --no-cache curl

COPY . .

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip setuptools wheel && \
    pip install -r requirements.txt

CMD ["python", "app.py"]