FROM python:3.8-slim-buster

WORKDIR /app

RUN sed -i 's/deb.debian.org/archive.debian.org/g; s|security.debian.org|archive.debian.org/debian-security|g' /etc/apt/sources.list

RUN apt update
RUN apt install -y curl

COPY . .

RUN pip install -r requirements.txt

CMD python app.py