FROM python:3.11-alpine

WORKDIR /app

RUN apk add --no-cache curl

COPY . .

RUN pip install --no-cache-dir --upgrade pip setuptools wheel && \
    pip install --no-cache-dir -r requirements.txt

CMD ["python", "app.py"]