services:
  app1:
    build: ../app
    hostname: app1
    ports:
      - "7001:5000"

  app2:
    build: ../app
    hostname: app2
    ports:
      - "7002:5000"

  app3:
    build: ../app
    hostname: app3
    ports:
      - "7003:5000"
